name: potion_riders
description: App mobile per il gioco sociale Potion Riders
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.7

  #json image_picker:
  file_picker: ^10.1.9

  excel: ^2.1.0

  # Google Sign In
  google_sign_in: ^6.2.2


  # Provider per la gestione dello stato
  provider: ^6.0.5

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0

  # Utility
  intl: ^0.18.1

  # uuid
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700